### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by Morkendi** [Morkendi/Weather-Dashboard#2]
# CSS
## To-Do's
- Add styling:
    - Header
    - City search
    - "Search" button
    - City search history
    - City information
    - 5 day forecast section
## Completion Criteria
- All styling is complete
- There is no repeting styling in different section

**Comment by Morkendi** [comment]
# Initial addition
Added styles to entire document.
##Pending
- Style forecast cards

**Comment by anshuu23** [comment]
hi , i can make website responsive and interactive .
